import { Injectable } from '@angular/core';
@Injectable({
  providedIn: 'root'
})
export class EnANdAeJson {
    constructor() { }
    getArabicConent(){
        let aeData;
        return aeData={
            // <-----------------login---------->
            'Enter_mobile_number':'الرجاء إدخال رقم الموبايل',
            'Continue':'المتابعة',
            'Cancel':'إلغاء',
            'Choose_Your_country':'الرجاء إختيار الدولة',
            'OTP_sent_to_your_number':'تم إرسال كلمة السر لمرة واحدة على رقم موبايلك',
            'Please_verify_the_OTP_by_entering_the_below':'الرجاء تأكيد كلمة السر لمرة واحدة من خلال كتابة الرمز أدناه',
            'Resend':'إعادة الإرسال',
            'Change_number':'تغيير الرقم',
            'Gender_Selection':'إختيار الجنس',
            // <-----------------home---------->
            'Order_for_Stitching':'طلب خياطة جديد',
            'Home':'الصفحة الرئيسية',
            'Dashboard':'لوحة البيانات',
            'Analytics':'التحليلات',
            'Manage_Promotions':'إدارة العروض',
            'Completed':'مكتملة',
            'Pending':'قيد الإجراء',
            'Submitted':'تم التقديم',
            'Buyer_Request':'عروض الأسعار',
            'Quotation':'عروض الأسعار',
            'Order_Details':'تفاصيل الطلبات',
            'Appointment_List':'قائمة المواعيد',

// <-------------skill-update-page--------------->
            'Skills_Product_Update':'المهارات والمنتجات',
            'Skills':'المهارات',
            'Products':'المنتجات',
            'Material_Mapping':'إختيار الأقمشة',
            'Dress_Type':'نوع الثوب',
            'Material_Type':'نوع القماش',
            'Measurement_Type':'نوع المقاس',
            'Stitching_Time':'زمن الخياطة',
            'Location':'الموقع',
            'Product_Mapping':'إختيار المنتجات',
            'Add_New_Product':'إضافة منتج جديد',
            'Remove':'حذف',
            'Sub_Dress_Type':'نوع القوب الفرعي',
            'Branches':'الفروع',
            'Measurements':'المقاسات',
            'Choose_Country':'إختيار الدولة',
            'Choose_Area':'إختيار المنطقة',
            'Select_All':'إختيار الكل',
            // <--------Add-new-product------>
            'upload':'رفع',
            'Category':'التصنيفات',
            'Product_Name_In_English':'اسم المنتج باللغة الانجليزية',
            'Product_Name_In_Arabic':'اسم المنتج باللغة العربية',
            'Add_Description_in_English':'اكتب التفصيل باللغة الانجليزية',
            'Add_Description_in_Arabic':'اكتب التفصيل باللغة العربية',
            'SKU':'رمز تعريف المنتج',
            'My_own_Product':'منتجاتي الخاصة',
            'Product_Units_CM':'وحدة قياس المنتج(سم)',
            'EU_Size_Guide':'الاتحاد الأوروبي (دليل المقاسات)',
            'Price':'السعر',
            'Save':'حفظ',
            'Description':'التفصيل',
            // <--------Category------>
            'Select':'إختيار',
            'Choose_Catogery':'إختيار التصنيف',
            // <--------product-list------>
            'Search_Products':'إبحث عن منتجات',
            // <--------rejected-details------>
            'Rejected_Reasons':'سبب الرفض',
            // <-------material-map---------->
            'Mapped':'تم الإختيار',
            'Express':'مستعجل',
            // <-------material-map-detail---------->
            'Material Details':'تفصيل الأقمشة',
            'Material':'الأقمشة',
            'Seasonal':'الموسم',
            'Place_of_Industry':'بلد المنشأ',
            'Brands':'الماركة',
            'Color':'اللون',
            'Thickness':'السماكة',
            'I_have_the_material':'لدي هذا القماش',
            'Friendly_Name_In_English':'الاسم المتعارف عليه لدي باللغة الانجليزية',
            'Friendly_Name_In_Arabic':'الاسم المتعارف عليه لدي باللغة العربية',
            // <-------dress-type-detail---------->
            'Details':'التفاصيل',
            'I_Stitch_This_Dress':'يمكنني خياطة هذا الثوب',
            'Customization':'التعديلات والإضافات',
            'Stitching_Charges':'رسوم الخياطة',
            'Time_Required_for_Stitching':'الزمن المطلوب للخياطة',
            'Material_Charges':'سعر القماش',
            'Customization_Image':'صور التعديلات والاضافات',
            'Customization_Details':'تفاصيل التعديلات والإضافات',

            // <-------------profile-------------->
           
            'Personal_Info':'البيانات الشخصية',
            'Gender':'الجنس',
            'Edit_Profile':'تعديل الملف الشخصي',
            'Update':'تعديل',
            'IsActive':'فعال؟',
            'Enter_English_Name':'أدخل الاسم باللغة الانجليزية',
            'Enter_Arabic_Name':'أدخل الاسم باللغة العربية',
            'Enter_Your_Email':'أدخل الايميل الإلكتروني',
            'Enter_Date_Of_Birth':'أدخل تاريخ الميلاد',
            'Enter_First_Name':'أدخل الاسم الاول',
            'Enter_Second_Name':'أدخل الكنية',
            'Name_in_English':'اسم الفرع باللغة الانجليزية',
            'Name_in_Arabic':'اسم الفرع باللغة العربية',
            'Select_Country':'إختيار الدولة',
            'Select_State':'أختيار المدينة',
            'Area':'المنطقة',
            'Address_in_English':'العنوان باللغة الانجليزية',
            'Address_in_Arabic':'العنوان باللغة العربية',
            'Landmark':'معلم قريب',
            'Branch_Details':'تفاصيل الفروع',
            'Location_Address':'عنوان الموقع',
            'Edit':'تعديل',
            'Shop_Images':'صور المحل',
            'Upload':'رفع',
            'Confirm_Location':'تأكيد الموقع',
            'choose_from_map':'إختيار من الخريطة',
// <------------------order-management------------>
'Order_Pending':'الطلبات تحت الإجراء',
'Order_Date':'تاريخ الطلب',
'Order_Id':'معرف الطلب',
'Product_Name':'اسم المنتج',
'No_Data_Found':'لاتوجد بيانات متاحة',

'Pending_Order_Details':'تفاصيل الطلبات تحت الإجراء',
'Items':'المنتجات',
'Order_No':'رقم الطلب',
'Order_Total_Amount':'قيمة الطلب الاجمالي',
'Delivery_Type':'نوع التوصيل',
'Order_Type':'نوع الطلب',
'Stitching_Type':'نوع الخياطة',
'Quantity':'الكمية',
'Total':'الاجمالي',
'Status':'الحالة',
'Measurement_Appointment':'موعد اخذ المقاس',
'Create_AppointMent':'إنشاء موعد',
'Approve_AppointMent':'الموافقة على موعد',
'Appointment_Type':'نوع الموعد',
'AppointMent_Date':'تاريخ الموعد',
'AppointMent_Time':'وقت الموعد',
'AppointMent_Status':'حالة الموعد',
'Appointment_will_be_visible_once_Buyer_updates_the_appointment_details':'سيكون الموعد متاحا بمجرد قيام المشتري بتحديث تفاصيل الموعد',
'Appointment_will_be_visible_once_you_updates_the_appointment_details':'سيكون الموعد متاحا بمجرد قيامك بتحديث تفاصيل الموعد',
'EdMaterial_Appointmentit':'موعد الأقمشة',
'MeasureMent':'المقاسات',
'Reference_Image':'الصور المرجعية',
'Update_Status':'تحديث حالة الطلب',
'Size':'الحجم',
'Qty':'الكمية',
'Brand':'الماركة',
'Price_Details':'تفاصيل السعر',
'Stitching_And_Material_Charges':'رسوم القماش والخياطة',
'MeasureMent_Charges':'رسوم أخذ المقاس',
'Urgent_Stitching_Charges':'رسوم خياطة مستعجلة',
'Delivery_Charges':'رسوم التوصيل',
'Material_Delivery_Charges':'رسوم استلام وتوصيل الأقمشة',
'Total_AED':'الاجمالي بالدرهم',
'Store_Products':'منتجات المتجر',
'Grand_Total_AED':'الاجمالي بالدرهم',
'Payment_Status':'حالة الدفع',
'Delivery_Information':'بيانات التوصيل',
'Customization_is_Empty':'التعديلات والغضافات فارغة',
'Track_Order':'تتبع الطلب',
'Rating_and_Write_a_Review':'تقييم وكتابة مراجعة',
'Tailor_Rating_and_Review':'تقييم وكتابة مراجعة عن الخياط',
'Material_Rating_and_Review':'تقييم وكتابة مراجعة عن الأقمشة',

// <------create-appointmet----------->
'Appointment_Details':'تفاصيل الموعد',
'Shop_Name':'اسم المحل',
'Appointment Type':'نوع الموعد',
'Date':'التاريخ',
'Select_date':'اختر التاريخ',
'Time_Slot':'اختر الوقت',
'Appointment_Status':'حالة الموعد',
'Choose_Your_TimeSlot':'اختر الوقت',
// <---------delivered---------->
'Delivered_Order_Details':'تفاصيل الطلبات المسلمة',
'Order_Completed':'الطلبات المكتملة',
// <---------Material---------->
'Material_Selection':'اختيار الاقمشة',
'Place_Of_Industry':'بلد المنشأ',
'Preview':'معاينة',
// <---------Measurement---------->
'Measurement_Details':'بيانات المقاسات',
'Measurement_By':'تم أخذ المقاس من طرف',
'Add_new_measurement':'إضافة مقاس جديد',
'Measurement_Name_for':'اسم المقاس ل',
'Measurement_Name':'اسم المقاس',
'min':'الحد الأدنى',
'max':'الحد الأقصى',
'Enter_value':'أدخل القيمة',
'Measurement':'المقاسات',
'Images':'الصور',
'Parts':'أعضاء الجسم',
// <---------Quotaion---------->
'Request_Id':'رقم الطلب',
'Buyer_Name':'اسم المشتري',
'Request_Date':'تاريخ الطلب',
'Request_Pending':'الطلبات تحت الإجراء',
'Approved_List':'القائمة المعتمدة',
'No_measurement_Found !':'لاتوجد مقاسات متاحة',
'Measurement_will_be_added_by_tailor_during_appointment':'سوف يتم إضافة المقاساتمن خلال الخياط خلال الوعد المحدد',
'Request_Details':'تفاصيل الطلب',
'Request_on':'تم الطلب بتاريخ',
'Sub_Dress':'الثوب الفرعي',
'Material_Details':'تفاصيل الأقمشة',
'Detail':'التفاصيل',
'Accept':'الموافقة',
'Reject':'الرفض',
'Measurment':'المقاسات',
'Order_is_Approve_After_Quoating_the_Price_and_Approximate_Delivery_Date':'سوف يتم اعتماد الطلب بعد تحديد السعر والوقت المتوقع لإنجاز الطلب',
'Ok':'حسنا',
'No_of_days_Required':'عدد الايام المطلوبة لإنجاز الطلب',
'Days':'يوم',
'Delivery_Date':'تاريخ التوصيل',
'Validity':'فترة الصلاحية',
'Oreder_Pricing_AED':'تسعير الطلب (بالدرهم)',
'Measurement_Charges':'رسوم أخذ المقاسات',
'MaterialCollection_Charges':'رسوم استلام وتسليم الأقمشة',
'CONTINUE':'المتابعة',
// <---------Promotions---------->
'Promotions':'العروض',
'Ongoing_Promotions':'العروض الحالية',
'Expired_Promotions':'العروض المنتهية',
'Promo_Code':'الرمز الترويجي',
'Expires_On':'ينتهي بتاريخ',
'MiniMum_Order_Value':'الحد الأدنى للطلب',
'Minimum_Discount_Value':'الحد الأدنى للخصم',
'Create_New_Promotions':'إنشاء عرض جديد',
'Choose_Banner':'إختر البانر المطلوب',
'Choose_From_Templates':'إختر من القوالب',
'Upload_Your_Own_Material':'حمل البانر الخاص بك',
'Offer_Type':'نوع العرض',
'Flat':'خصم ثابت',
'Discount':'خصم بنسبة',
'Offer_Value':'قيمة العرض',
'Minimum_Order_Value':'الحد الأدنى للطلب',
'Maximun_Discount':'الحد الأقصى للخصم',
'Promotion_Starts_On':'العرض يبدأ بتاريخ',
'Promotion_Ends_On':'العرض ينتهي بتاريخ',
'Promotion_Applies_to':'العرض ينطبق على',
'Stitching':'الخياطة',
'Applying_Method':'طريقة تطبيق العرض',
'Promocode':'رمز ترويجي',
'Enter_Promo_Code':'اكتب الرمز الترويجي',
'Maximun_Discount_Amount':'الحد الاقصى للخصم',
'Promotion_Starting_Date':'تاريخ بداية العرض',
'Promotion_Ending_Date':'تاريخ نهاية العرض',
'Done':'تم',
'All_Banners':'جميع البانرات',
'Preffered_size_for_banner_630_220_pixel':'الحجم المفضل للبانر هو 630*220 بكسل',
'Choose_Stitching_Products':'اختر من منتجات الخياطة',
'Male':'ذكر',
'Female':'انثى',
'Boy':'طفل',
'Girl':'طفله',
'Next':'تقدم',
'Selected_Products':'المنتجات المختارة',
'All_Products':'جميع المنتجات',
'Choose_Store_Products':'اختر من منتجات المتجر',
'Catagories':'التصنيفات',
// <---------Menu---------->
'My_Account':'حسابي',
'Book_an_Appointment':'احجز موعد',
'Rejected_Quotation':'عروض الأسعار المرفوضة',
'Promotion':'العروض',
'Rejected_Products':'المنتجات المرفوضة',
'Terms_and_Condition':'الشروط والأحكام',
'Settings':'الإعدادات',
'Logout':'تسجيل الخروج',
'Notification':'التنبيهات',
// <---------intro page---------->
'Profile':'الملف الشخصي',
'Enter Valid Email !':'',
'Required !':'ممطلوب',
'Name !':'الاسم',
'Friendly_Name_in_Arabic':'',
'Email !':'الايميل',
// <---------shop=time---------->
// 'Choose_Your_TimeSlot':'الرجاء اختيار التوقيت',
'Store_Timings':'أوقات العمل',
// <---------------general--------------------->
'Add_more_hrs':'إضافة ساعات عمل',
'Sunday':'الأحد',
'Monday':'الإثنين',
'Tuesday':'الثلاثاء',
'Wednesday':'الأربعاء',
'Thursday':'الخميس',
'Friday':'الجمعة',
'Saturday':'السبت',
'Choose_Your_days':'الأيام التي تحتاجها ',
'Choose_Your_Area':'اختر المدينة',
'Choose_Mediatype':'اختر نوع الميديا',
'Search':'البحث',
'CM':'سنتيمتر',
'Language_Settings':'إعدادات اللغة',
'Choose_Your_Language':'الرجاء إختيار اللغة',
'Approved_Details':'الموافقة على التفاصيل',
'Choose_State':'اختر المدينة',
'Order_Earning':'والإيرادات الطلبات ',
'Recieved':'المسلمة',
'Payment':'الدفعات',
'User_Review':'تقييم العملاء',
'Choose_Your_State':'اختر المدينة'
        }
    }
}